name: cus_movil
description: "App móvil de Clave Única Sanjuanense"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^29.1.38
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  http: ^1.4.0
  xml: ^6.5.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  provider: ^6.1.5
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.0.4
  confetti: ^0.7.0
  file_picker: ^8.1.2
  path: ^1.9.0
  flutter_pdfview: ^1.2.7
  path_provider: ^2.1.2
  syncfusion_flutter_core: ^29.2.11
  liquid_progress_indicator_v2: ^0.5.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  lottie: ^3.0.0
  logger: ^2.6.1
  permission_handler: ^11.3.1
  flutter_cache_manager: ^3.4.1
  permission_handler_android: ^12.1.0
  shimmer: ^3.0.0
  http_parser: ^4.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  path_provider:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env